# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: MyPersonalPC
  demands:
    - Agent.Name -equals ThinkpadE14

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'Path'
    jdkDirectory: '$(JAVA_HOME)'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'test -PRegression'

- task: SendEmail@1
  condition: always()
  inputs:
    To: 'nsr.kpma@gmail.com'
    From: 'nsr01734@gmail.com'
    Subject: 'Selenium Test Report'
    Body: 'Pls find the report in attachment'
    BodyAsHtml: false
    AddAttachment: false
    SmtpServer: 'smtp.gmail.com'
    SmtpPort: '465'
    SmtpUsername: 'nsr01734@gmail.com'
    SmtpPassword: 'howfcysmetyfnjsk'